<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\DocumentType;

class DocumentTypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $documentTypes = [
            [
                'name' => 'Passport',
                'code' => 'PASSPORT',
                'description' => 'Valid passport copy',
                'category' => 'identification',
                'is_required' => true,
                'has_expiry' => true,
                'allowed_file_types' => ['pdf', 'jpg', 'jpeg', 'png'],
                'max_file_size' => 5120,
                'sort_order' => 1,
                'allows_multiple_files' => false,
                'max_files' => 1,
            ],
            [
                'name' => 'Birth Certificate',
                'code' => 'BIRTH_CERT',
                'description' => 'Birth certificate copy',
                'category' => 'identification',
                'is_required' => false,
                'has_expiry' => false,
                'allowed_file_types' => ['pdf', 'jpg', 'jpeg', 'png'],
                'max_file_size' => 5120,
                'sort_order' => 2,
                'allows_multiple_files' => false,
                'max_files' => 1,
            ],
            [
                'name' => 'Academic Transcripts',
                'code' => 'TRANSCRIPTS',
                'description' => 'High school or previous academic transcripts',
                'category' => 'academic',
                'is_required' => true,
                'has_expiry' => false,
                'allowed_file_types' => ['pdf', 'doc', 'docx'],
                'max_file_size' => 10240,
                'sort_order' => 3,
                'allows_multiple_files' => true,
                'max_files' => 5,
            ],
            [
                'name' => 'Degree Certificate',
                'code' => 'DEGREE_CERT',
                'description' => 'Previous degree certificate',
                'category' => 'academic',
                'is_required' => false,
                'has_expiry' => false,
                'allowed_file_types' => ['pdf', 'jpg', 'jpeg', 'png'],
                'max_file_size' => 5120,
                'sort_order' => 4,
                'allows_multiple_files' => false,
                'max_files' => 1,
            ],
            [
                'name' => 'IELTS Score',
                'code' => 'IELTS',
                'description' => 'IELTS test score report',
                'category' => 'academic',
                'is_required' => true,
                'has_expiry' => true,
                'allowed_file_types' => ['pdf', 'jpg', 'jpeg', 'png'],
                'max_file_size' => 5120,
                'sort_order' => 5,
                'allows_multiple_files' => false,
                'max_files' => 1,
            ],
            [
                'name' => 'TOEFL Score',
                'code' => 'TOEFL',
                'description' => 'TOEFL test score report',
                'category' => 'academic',
                'is_required' => false,
                'has_expiry' => true,
                'allowed_file_types' => ['pdf', 'jpg', 'jpeg', 'png'],
                'max_file_size' => 5120,
                'sort_order' => 6,
                'allows_multiple_files' => false,
                'max_files' => 1,
            ],
            [
                'name' => 'Bank Statement',
                'code' => 'BANK_STATEMENT',
                'description' => 'Recent bank statement showing funds',
                'category' => 'financial',
                'is_required' => true,
                'has_expiry' => true,
                'allowed_file_types' => ['pdf', 'jpg', 'jpeg', 'png'],
                'max_file_size' => 5120,
                'sort_order' => 7,
                'allows_multiple_files' => false,
                'max_files' => 1,
            ],
            [
                'name' => 'Sponsorship Letter',
                'code' => 'SPONSORSHIP',
                'description' => 'Letter of financial sponsorship',
                'category' => 'financial',
                'is_required' => false,
                'has_expiry' => false,
                'allowed_file_types' => ['pdf', 'doc', 'docx'],
                'max_file_size' => 5120,
                'sort_order' => 8,
                'allows_multiple_files' => false,
                'max_files' => 1,
            ],
            [
                'name' => 'Student Visa',
                'code' => 'STUDENT_VISA',
                'description' => 'Student visa copy',
                'category' => 'visa',
                'is_required' => false,
                'has_expiry' => true,
                'allowed_file_types' => ['pdf', 'jpg', 'jpeg', 'png'],
                'max_file_size' => 5120,
                'sort_order' => 9,
                'allows_multiple_files' => false,
                'max_files' => 1,
            ],
            [
                'name' => 'Medical Certificate',
                'code' => 'MEDICAL_CERT',
                'description' => 'Medical fitness certificate',
                'category' => 'medical',
                'is_required' => false,
                'has_expiry' => true,
                'allowed_file_types' => ['pdf', 'jpg', 'jpeg', 'png'],
                'max_file_size' => 5120,
                'sort_order' => 10,
                'allows_multiple_files' => false,
                'max_files' => 1,
            ],
            [
                'name' => 'Police Clearance',
                'code' => 'POLICE_CLEARANCE',
                'description' => 'Police clearance certificate',
                'category' => 'identification',
                'is_required' => false,
                'has_expiry' => true,
                'allowed_file_types' => ['pdf', 'jpg', 'jpeg', 'png'],
                'max_file_size' => 5120,
                'sort_order' => 11,
                'allows_multiple_files' => false,
                'max_files' => 1,
            ],
            [
                'name' => 'Letter of Recommendation',
                'code' => 'RECOMMENDATION',
                'description' => 'Academic or professional recommendation letter',
                'category' => 'academic',
                'is_required' => false,
                'has_expiry' => false,
                'allowed_file_types' => ['pdf', 'doc', 'docx'],
                'max_file_size' => 5120,
                'sort_order' => 12,
                'allows_multiple_files' => false,
                'max_files' => 1,
            ],
            [
                'name' => 'Statement of Purpose',
                'code' => 'SOP',
                'description' => 'Personal statement or statement of purpose',
                'category' => 'academic',
                'is_required' => false,
                'has_expiry' => false,
                'allowed_file_types' => ['pdf', 'doc', 'docx'],
                'max_file_size' => 5120,
                'sort_order' => 13,
                'allows_multiple_files' => false,
                'max_files' => 1,
            ],
            [
                'name' => 'Resume/CV',
                'code' => 'RESUME',
                'description' => 'Current resume or curriculum vitae',
                'category' => 'other',
                'is_required' => false,
                'has_expiry' => false,
                'allowed_file_types' => ['pdf', 'doc', 'docx'],
                'max_file_size' => 5120,
                'sort_order' => 14,
            ],
        ];

        foreach ($documentTypes as $type) {
            DocumentType::create($type);
        }
    }
}
